image: alpine:latest

stages:
  - license_checking
  - deploy

license_checking:
  stage: license_checking
  image:
    name: python:3.11
  script:
    - python -m venv venv
    - source venv/bin/activate
    - python main.py
  allow_failure: true

deployment:
  stage: deploy
  image:
    name: docker:latest
  script:
    - echo "$ROBOT_PASSWORD" | docker login $HARBOR_URL -u "robot\$$ROBOT_NAME" --password-stdin
    - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME .
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME $HARBOR_HOST/$HARBOR_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
